services:
  existarr:
    image: ghcr.io/xxfantasiadownxx/existarr:latest
    container_name: existarr
    ports:
      - "5100:5100"
    environment:
      - TVDB_API_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - MEDIA_ROOT=/media
    volumes:
      - /path/to/media/:/media:ro
      - ./data:/data
    restart: unless-stopped
